import { spawn, ChildProcess } from 'child_process';
import { EventEmitter } from 'events';
import { logger } from '../loggerService';

export class Decoder extends EventEmitter {
  private ffmpegProcess: ChildProcess | null = null;
  private firstFrameDecoded: boolean = false;
  private totalFramesDecoded: number = 0;

  public start(codec: string = 'h264'): void {
    logger.info(`[Scrcpy] Decoder initialized for codec: ${codec}`, 'Decoder');

    // Use raw demuxer (-f h264 / hevc / av1) for raw Scrcpy NAL stream input
    const format = codec === 'h265' || codec === 'hevc' ? 'hevc' : codec === 'av1' ? 'av1' : 'h264';

    const ffmpegArgs = [
      '-an',
      '-f', format,
      '-i', 'pipe:0',
      '-f', 'image2pipe',
      '-vcodec', 'mjpeg',
      '-q:v', '4',
      '-'
    ];

    this.ffmpegProcess = spawn('ffmpeg', ffmpegArgs);

    this.ffmpegProcess.on('error', (err) => {
      logger.error(`[Scrcpy] FFmpeg process spawn error: ${err.message}`, 'Decoder');
    });

    this.ffmpegProcess.on('exit', (code, signal) => {
      logger.info(`[Scrcpy] Decoder process exited code=${code} signal=${signal}`, 'Decoder');
    });

    this.ffmpegProcess.stderr?.on('data', (data) => {
      const errStr = data.toString().trim();
      if (errStr) {
        logger.info(`[FFmpeg stderr] ${errStr}`, 'Decoder');
      }
    });

    let buffer = Buffer.alloc(0);
    this.ffmpegProcess.stdout?.on('data', (chunk: Buffer) => {
      buffer = Buffer.concat([buffer, chunk]);

      let offset = 0;
      while (offset < buffer.length - 1) {
        // Find JPEG SOI (FF D8)
        const start = buffer.indexOf(Buffer.from([0xff, 0xd8]), offset);
        if (start === -1) break;

        // Find JPEG EOI (FF D9)
        const end = buffer.indexOf(Buffer.from([0xff, 0xd9]), start + 2);
        if (end === -1) break;

        const frame = buffer.subarray(start, end + 2);
        this.totalFramesDecoded++;
        if (!this.firstFrameDecoded) {
          this.firstFrameDecoded = true;
          logger.info('[Scrcpy] First frame generated by decoder', 'Decoder');
        }

        logger.info(`[Scrcpy] FRAME DECODED (${frame.length} bytes)`, 'Decoder');

        if (this.totalFramesDecoded % 30 === 0) {
          logger.info(`[Scrcpy] Frames rendered: ${this.totalFramesDecoded}`, 'Decoder');
        }

        this.emit('frame', frame);
        offset = end + 2;
      }

      if (offset > 0) {
        buffer = buffer.subarray(offset);
      }
    });
  }

  public write(chunk: Buffer): void {
    if (this.ffmpegProcess && this.ffmpegProcess.stdin && !this.ffmpegProcess.stdin.destroyed) {
      logger.info(`[Scrcpy] DECODE CALLED (${chunk.length} bytes)`, 'Decoder');
      this.ffmpegProcess.stdin.write(chunk);
    }
  }

  public stop(): void {
    if (this.ffmpegProcess) {
      this.ffmpegProcess.kill('SIGTERM');
      this.ffmpegProcess = null;
    }
    this.firstFrameDecoded = false;
    this.totalFramesDecoded = 0;
  }
}
