import { spawn, ChildProcess } from 'child_process';
import { EventEmitter } from 'events';
import { logger } from '../loggerService';

export class Decoder extends EventEmitter {
  private ffmpegProcess: ChildProcess | null = null;
  private firstFrameDecoded: boolean = false;

  public start(codec: string = 'h264'): void {
    logger.info(`decoder initialized for codec: ${codec}`, 'Decoder');

    const ffmpegArgs = [
      '-an',
      '-f', 'matroska',
      '-i', 'pipe:0',
      '-f', 'image2pipe',
      '-vcodec', 'mjpeg',
      '-q:v', '4',
      '-'
    ];

    this.ffmpegProcess = spawn('ffmpeg', ffmpegArgs);

    this.ffmpegProcess.stderr?.on('data', (data) => {
      const errStr = data.toString().trim();
      if (errStr.toLowerCase().includes('error')) {
        logger.warn(`decoder errors: ${errStr}`, 'Decoder');
      }
    });

    let buffer = Buffer.alloc(0);
    this.ffmpegProcess.stdout?.on('data', (chunk: Buffer) => {
      buffer = Buffer.concat([buffer, chunk]);

      let offset = 0;
      while (offset < buffer.length - 1) {
        // Find JPEG SOI (FF D8)
        const start = buffer.indexOf(Buffer.from([0xff, 0xd8]), offset);
        if (start === -1) break;

        // Find JPEG EOI (FF D9)
        const end = buffer.indexOf(Buffer.from([0xff, 0xd9]), start + 2);
        if (end === -1) break;

        const frame = buffer.subarray(start, end + 2);
        if (!this.firstFrameDecoded) {
          this.firstFrameDecoded = true;
          logger.info('first decoded frame generated by decoder', 'Decoder');
        }

        this.emit('frame', frame);
        offset = end + 2;
      }

      if (offset > 0) {
        buffer = buffer.subarray(offset);
      }
    });
  }

  public write(chunk: Buffer): void {
    if (this.ffmpegProcess && this.ffmpegProcess.stdin && !this.ffmpegProcess.stdin.destroyed) {
      this.ffmpegProcess.stdin.write(chunk);
    }
  }

  public stop(): void {
    if (this.ffmpegProcess) {
      this.ffmpegProcess.kill('SIGTERM');
      this.ffmpegProcess = null;
    }
    this.firstFrameDecoded = false;
  }
}
